/* This file is autogenerated on every build */
type NodeWorkerPaths = { [key in 'hotReloadWatcher' | 'intervalMessage' | 'someMessage']: string }
type BrowserWorkerPaths = { [key in never]: string }
