import { spawnSync } from 'child_process'
import { rimrafSync } from 'rimraf'

import { getDirs } from './libs/constants'
import { colorize, print } from './libs/utils'

main()

function main() {
  const { electron, nodeModules } = getDirs()
  const autoGeneratedSuffix: AutoGeneratedSuffix = '.autogenerated.'
  print(
    colorize({ bg: 'red', text: '[WARNING]' }),
    'PURGING ENTIRE PROJECT NON-GIT ITEMS AND RESET ALL UNCOMMITED CHANGES',
  )
  rimrafSync('.', {
    filter: (path) => [electron, nodeModules, autoGeneratedSuffix].some((matcher) => new RegExp(matcher).test(path)),
  })
  spawnSync('git reset --hard', { shell: true })
  print(colorize({ bg: 'blue', text: '[INFO]' }), 'Purging complete')
  print(
    colorize({ bg: 'blue', text: '[INFO]' }),
    'Eslint WILL complain on most files after purging due to the missing of node_modules',
  )
  print(
    colorize({ bg: 'blue', text: '[INFO]' }),
    'Execute `npm install` [and reload code editor (Recommended)] before running any other commands',
  )
}
